name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"

      - name: Build Device (Debug, no signing)
        run: |
          xcodebuild \
            -project Aegis.xcodeproj \
            -scheme Device \
            -configuration Debug \
            -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Run tests
        run: |
          xcodebuild \
            -project Aegis.xcodeproj \
            -scheme Device \
            -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            test
        continue-on-error: true
